export enum TypeNames {
  LOAD_EMPLOYEES = 'WORKMOTION/EMPLOYEE/LOAD',
  UPDATE_SINGLE_EMPLOYEE = 'WORKMOTION/EMPLOYEE/UPDATE_SINGLE',
  LOAD_SINGLE_EMPLOYEE = 'WORKMOTION/EMPLOYEE/LOAD_SINGLE',
  REMOVE_SINGLE_EMPLOYEE = 'WORKMOTION/EMPLOYEE/REMOVE_SINGLE',
}